### ISSUE TITLE
Feature Request: Convert Azure Kinect JSON file to BVH

### ISSUE THREAD

**Issue by IAmNatch** [Mirevi/MotionHub#1]
Hi there,

Thanks investing your time on this valuable project!

It seems like this codebase has the key pieces to convert Azure Kinect JSON data into another format, such as BVH. I wonder if, in addition the current unity system, you'd consider implementing a "CLI Mode" where users could input a Azure Kinect JSON and receive a BVH file as output.

**Comment by phladwig** [comment]
Hi, 
thanks for your request. 

Are you referring to this JSON generation? [https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/offline_processor](https://github.com/microsoft/Azure-Kinect-Samples/tree/master/body-tracking-samples/offline_processor) ?
